from gymnasium.envs.registration import register

register(
    id="GridWorld-v0",
    entry_point="babybot01_env.envs:GridWorldEnv",
)
register(
    id="Spidy-v0",
    entry_point="babybot01_env.envs:SpidyEnv",
)
register(
    id="Spidy-v2",
    entry_point="babybot01_env.envs:SpidyEnvV2",
)
register(
    id="Spidy-v3",
    entry_point="babybot01_env.envs:SpidyEnvV3",
)
register(
    id="Spidy-v4",
    entry_point="babybot01_env.envs:SpidyEnvV4",
)
register(
    id="Spidy-v4_1",
    entry_point="babybot01_env.envs:SpidyEnvV4_1",
)
register(
    id="Spidy-v4_2",
    entry_point="babybot01_env.envs:SpidyEnvV4_2",
)
register(
    id="Spidy-v4_3",
    entry_point="babybot01_env.envs:SpidyEnvV4_3",
)
register(
    id="Spidy-v4_4",
    entry_point="babybot01_env.envs:SpidyEnvV4_4",
)

