[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["babybot01_env"]

[project]
name = "babybot01_env"
version = "0.1.0"
dependencies = [
  "gymnasium",
  "pygame>=2.1.3",
  "pre-commit",
]
